export const EDUCATIONAL_STAGES = {
  BASIC_EDUCATION: "BASIC_EDUCATION",
  ENTRANCE_EXAM: "ENTRANCE_EXAM",
  COLLEGE: "COLLEGE",
  PROFESSIONAL: "PROFESSIONAL",
  BOARD_EXAM: "BOARD_EXAM",
  CERTIFICATION: "CERTIFICATION",
  CONTINUING_EDUCATION: "CONTINUING_EDUCATION",
} as const;

export type EducationalStage =
  (typeof EDUCATIONAL_STAGES)[keyof typeof EDUCATIONAL_STAGES];

export const GRADE_LEVELS = {
  GRADE_1: "GRADE_1",
  GRADE_2: "GRADE_2",
  GRADE_3: "GRADE_3",
  GRADE_4: "GRADE_4",
  GRADE_5: "GRADE_5",
  GRADE_6: "GRADE_6",
  GRADE_7: "GRADE_7",
  GRADE_8: "GRADE_8",
  GRADE_9: "GRADE_9",
  GRADE_10: "GRADE_10",
  GRADE_11: "GRADE_11",
  GRADE_12: "GRADE_12",
  FIRST_YEAR: "FIRST_YEAR",
  SECOND_YEAR: "SECOND_YEAR",
  THIRD_YEAR: "THIRD_YEAR",
  FOURTH_YEAR: "FOURTH_YEAR",
} as const;

export type GradeLevel = (typeof GRADE_LEVELS)[keyof typeof GRADE_LEVELS];
